# This is the main Gitpod configuration file.
# It controls the base image, how the workspace initializes, which tasks run, and which ports are exposed.

image:
  file: .gitpod.Dockerfile  # Specifies that Gitpod should build and use the Docker image defined in .gitpod.Dockerfile in this repository.

tasks:
  - name: Setup Environment and Start Lago  # Label for this task (shown in Gitpod UI).
    init: |
      # Generate and set up environment variables if they don't exist
      if [ ! -f .env ]; then
        echo "Setting up environment variables..."
        echo "LAGO_RSA_PRIVATE_KEY=\"$(openssl genrsa 2048 | base64)\"" > .env
        echo "LAGO_DISABLE_SEGMENT=true" >> .env
        echo "LAGO_DISABLE_WALLET_REFRESH=true" >> .env
        echo "LAGO_REDIS_CACHE_PASSWORD=" >> .env
        echo "LAGO_AWS_S3_ENDPOINT=" >> .env
      fi
      
      # Source the environment variables
      set -a
      source .env
      set +a
      
      # Start Docker and run Lago
      bash .gitpod.docker-init.sh
      docker compose up --build -d
    command: |
      echo "Environment setup complete. Checking container status..."
      docker ps

ports:
  - port: 80  # Frontend port
    onOpen: open-preview
  - port: 3000  # API port
    onOpen: open-preview
