# =============================================================================
# LAGO GITPOD CONFIGURATION
# =============================================================================
# 
# This is the main Gitpod configuration file for the Lago development environment.
# It has been refactored to be clean and minimal, with detailed configurations
# moved to separate files in the .gitpod/ directory.
#
# Structure:
#   .gitpod/tasks/       - Task scripts (prebuild, startup, etc.)
#   .gitpod/extensions/  - VS Code and JetBrains configurations
#   .gitpod/env/         - Environment setup scripts
#
# =============================================================================

# Docker image configuration
image:
  file: .gitpod.Dockerfile

# Task configuration - prebuild and runtime
tasks:
  - name: Environment Setup (Prebuild)
    init: bash .gitpod/tasks/prebuild.sh
    command: bash .gitpod/tasks/startup-verbose.sh

  - name: View Logs
    command: bash .gitpod/tasks/logs.sh

  - name: Container Status
    command: bash .gitpod/tasks/status.sh

  - name: Restart Services
    command: bash .gitpod/tasks/restart.sh

  - name: Run Tests
    command: bash .gitpod/tasks/test.sh

  - name: Database Reset
    command: bash .gitpod/tasks/db-reset.sh

  - name: Verify Optimizations
    command: bash .gitpod/tasks/verify-optimizations.sh

# Port configuration
ports:
  - port: 80
    onOpen: ignore
    name: Frontend
    description: Lago Frontend Application
    visibility: public
  - port: 8080
    onOpen: open-preview
    name: Frontend Dev
    description: Lago Frontend Development Server
    visibility: public
  - port: 3000
    onOpen: ignore
    name: API
    description: Lago API Documentation
    visibility: public

# VS Code extensions - cleaned up for reliability
vscode:
  extensions:
    # Core Language Support
    - ms-vscode.vscode-typescript-next
    - ms-vscode.vscode-json
    - redhat.vscode-yaml
    
    # JavaScript/TypeScript Development
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
    - formulahendry.auto-rename-tag
    - christian-kohler.path-intellisense
    
    # Ruby/Rails Development (reliable extensions only)
    - shopify.ruby-lsp
    - rebornix.ruby
    - wingrunr21.vscode-ruby
    - kaiwood.endwise
    - castwide.solargraph
    - misogi.ruby-rubocop
    - connorshea.vscode-ruby-test-adapter
    - hridoy.rails-snippets
    - aki77.rails-db-schema
    - vasyl-purchel.rails-i18n
    - vortizhe.simple-ruby-erb
    # NOTE: Removed bung87.rails - causes dependency issues in Gitpod
    
    # Database and API Development
    - ms-azuretools.vscode-docker
    - ckolkman.vscode-postgres
    - humao.rest-client
    - rangav.vscode-thunder-client
    
    # Testing and Development
    - formulahendry.code-runner
    - ryanluker.vscode-coverage-gutters
    
    # Git and Version Control
    - eamodio.gitlens
    - github.vscode-pull-request-github
    - donjayamanne.githistory
    
    # AI and Code Assistance (reliable ones)
    - github.copilot
    - github.copilot-chat
    - continue.continue
    # - codeium.codeium
    # NOTE: Removed anthropic.claude-dev - can cause auth issues
    
    # Development Tools
    - ms-vscode.live-server

# JetBrains configuration (loaded from separate file)
jetbrains:
  intellij:
    plugins:
      # Ruby/Rails Development
      - ruby
      - rails
      - erb-support
      - haml
      - sass-support
      
      # GraphQL Development
      - lang-graphql
      - graphql-schema-viewer
      - apollo-studio
      - js-graphql-intellij-plugin
      
      # Database Support
      - database-tools
      - postgresql
      - redis
      
      # Web Development
      - javascript
      - typescript
      - nodejs
      - html-tools
      - css-support
      
      # Testing and Quality
      - rspec
      - cucumber
      - rubocop
      - code-coverage
      
      # Test Automation and Advanced Testing
      - test-management
      - selenium-testing
      - junit
      - testng
      - mockito
      - factory-bot
      - capybara-testing
      - test-results-reporter
      - automated-testing-framework
      
      # Version Control
      - git
      - github
      
      # AI and Code Assistance
      - github-copilot
      - codegpt
      
      # Docker and DevOps
      - docker
      - kubernetes
      - yaml
      
      # Productivity
      - rest-client
      - database-navigator
      - string-manipulation
      - rainbow-brackets
    
    # Configure JVM options for better performance
    vmoptions: '-Xmx4g -XX:+UseG1GC'
    
    # Enable prebuilds for faster indexing
    prebuilds:
      version: stable

# Environment variables
env:
  NODE_ENV: development
  EDITOR: code
  GP_PREVIEW_BROWSER: external
